services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:1.30.1.6562-915986d62
    restart: unless-stopped
    stop_grace_period: 3m
    environment:
      ADVERTISE_IP: ${ADVERTISE_IP}
      PLEX_CLAIM: ${PLEX_CLAIM}
      TZ: ${TZ}
    hostname: pms.home.local
    volumes:
      - ./config:/config
      - /tmp:/transcode
      - <path/to/media>:/data
    networks:
      - plexpms

networks:
  plexpms:
    driver: bridge
