services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:1.29.1.6316-f4cdfea9c
    restart: unless-stopped
    stop_grace_period: 3m
    environment:
      ADVERTISE_IP: ${ADVERTISE_IP}
      PGID: 1000
      PLEX_CLAIM: ${PLEX_CLAIM}
      PUID: 1000
      TZ: ${TZ}
    hostname: pms.home.local
    volumes:
      - ./config:/config
      - /tmp:/transcode
      - <path/to/media>:/data
    networks:
      - plexpms

networks:
  plexpms:
    driver: bridge
