version: '3.9'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:1.28.1.6104-788f82488
    restart: unless-stopped
    stop_grace_period: 3m
    environment:
      # TZ: CHANGEME
      ADVERTISE_IP: http://192.168.0.1:32400
      PUID: 1000
      PGID: 1000
    hostname: pms.home.local
    volumes:
      - ./config:/config
      - /tmp:/transcode
      - <path/to/media>:/data
    networks:
      - plexpms

networks:
  plexpms:
    driver: bridge
