version: '3.7'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:1.26.2.5797-5bd057d2b
    restart: unless-stopped
    stop_grace_period: 3m
    runtime: nvidia
    ports:
      - 32400:32400/tcp
      # GDM network discovery
      # ref: https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
      - 32410:32410/udp
      - 32412-32414:32412-32414/udp
    environment:
      # TZ: CHANGEME
      ADVERTISE_IP: http://192.168.0.1:32400
      PUID: 1000
      PGID: 1000
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
    hostname: pms.home.local
    volumes:
      - ./config:/config
      - /tmp:/transcode
      - <path/to/media>:/data
    networks:
      - plexpms

networks:
  plexpms:
    driver: bridge
